worker_processes auto;

error_log /dev/stderr warn;
pid /var/run/openresty.pid;

events {
    worker_connections 2048;
}

http {
    include       mime.types;
    default_type  application/json;

    lua_package_path "/usr/local/openresty/nginx/lua/?.lua;;";
    lua_socket_log_errors off;

    resolver 127.0.0.11 ipv6=off valid=10s;
    resolver_timeout 2s;

    lua_shared_dict upstreams 2m;
    lua_shared_dict cb_state 1m;

    map $http_x_api_key $client_key {
        default $http_x_api_key;
        ""      $binary_remote_addr;
    }

    limit_req_zone $client_key zone=per_key:10m rate=20r/s;
    limit_conn_zone $client_key zone=conn_per_key:10m;

    log_format gateway_json escape=json
        '{'
        '"time":"$time_iso8601",'
        '"request_id":"$request_id",'
        '"remote_addr":"$remote_addr",'
        '"method":"$request_method",'
        '"uri":"$request_uri",'
        '"status":$status,'
        '"body_bytes":$body_bytes_sent,'
        '"request_time":$request_time,'
        '"upstream_addr":"$upstream_addr",'
        '"upstream_status":"$upstream_status",'
        '"upstream_time":"$upstream_response_time",'
        '"client_id":"$client_id",'
        '"api_key_present":"$api_key_present",'
        '"user_agent":"$http_user_agent"'
        '}';

    upstream api_backend {
        server 0.0.0.0:1;
        balancer_by_lua_block {
            require("balancer").balance()
        }
        keepalive 32;
    }

    init_by_lua_block {
        require("apikeys").init()
    }

    init_worker_by_lua_block {
        require("discovery").start()
    }

    include /usr/local/openresty/nginx/conf/conf.d/*.conf;
}
