name: kantin-gateway

services:
  consul:
    image: hashicorp/consul:1.20
    container_name: kantin_consul
    command: ["agent", "-dev", "-client=0.0.0.0", "-ui", "-log-level=warn"]
    ports:
      - "8500:8500"
    networks:
      - gateway
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: ./dummy-api
    environment:
      CONSUL_HTTP_ADDR: http://consul:8500
      SERVICE_NAME: api
      SERVICE_PORT: "8080"
    depends_on:
      consul:
        condition: service_healthy
    deploy:
      replicas: 3
    networks:
      - gateway
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request;urllib.request.urlopen('http://127.0.0.1:8080/health')"]
      interval: 5s
      timeout: 3s
      retries: 20

  gateway:
    build: .
    container_name: kantin_gateway
    ports:
      - "8080:80"
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - gateway

networks:
  gateway:
    name: kantin_gateway
